import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import morgan from "morgan";
import helmet from "helmet";
import bodyParser from "body-parser";
import { connectToDatabase } from "./functions/database.js";
import DesignRoutes from "./routes/designRoutes.js";
import ProductRoutes from "./routes/productRoutes.js";
import UserRoutes from "./routes/UserRoutes.js";
import FabricRoutes from "./routes/fabricRoutes.js";
import StoreRoutes from "./routes/storeRoutes.js";
import dashboardRoutes from "./routes/dashboardRoutes.js";
import lalynnRoutes from "./routes/lalynnRoutes.js";
import StockProgramRoutes from "./routes/stockProgramRoutes.js";
import StockRoutes from "./routes/stockRoutes.js";
import "./functions/function.js";
import { io } from "./socket.io/index.js";
dotenv.config();
const app = express();
app.use(express.json());
app.use(helmet());
app.use(helmet.crossOriginResourcePolicy({ policy: "cross-origin" }));
app.use(morgan("common"));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cors());
app.use("/design", DesignRoutes);
app.use("/product", ProductRoutes);
app.use("/user", UserRoutes);
app.use("/fabric", FabricRoutes);
app.use("/store", StoreRoutes);
app.use("/dashboard", dashboardRoutes);
app.use("/lalynnwebsite", lalynnRoutes);
app.use("/stockApi", StockProgramRoutes);
app.use("/stock", StockRoutes);

connectToDatabase();
const port = parseInt(process.env.PORT) || 7070;
export const server = app.listen(port, () => {
  console.log(`helloworld: listening on http://localhost:${port}`);
});

// io.attach(server);
